w3c/websub

- index.html
updates them to either RFC7230 or RFC7231 as appropriate
> update RFC2616 references

- index.html
@aaronpk I'd love your feedback on this even if I mostly took your suggestion :)
> Protocol should allow for various types of sognature algorithms. 

- index.html
> remove recommendation about using From header

- index.html
> clarify lease_seconds is a non-negative decimal integer

- fpwd.html
- index.html
@dret Please let me know if that clarifies things!
> explicitly indicating that the list of algorithms can evolve. Fixes #21

- index.html
@aaronpk @voxpelli Please, take a look. I will address the diffing issue in a later PR.
> clarifying the use for fat pings. fixes #35

- index.html
> updated authors, fixes #57

- index.html
cc @aaronpk @dret @aaronpk 
Input welcome! I believe I did not change the initially described intent, but rephrased to make it clearer. (`.host-meta` issue to be addressed in another PR!)
> rephrased discovery section. Fixed #37

- index.html
> clarify the use of GET vs POST at the callback

- index.html
> add conformance classes and criteria

- index.html
> Add exit criteria

- index.html
> replace RFC3986 with WHATWG-URL

- index.html
> describe diffing mechanism for RSS and Atom

- index.html
> adding text about content negociation. fixes #86

- index.html
Cc @depressiveRobot @aaronpk (#88)
> adding a consideration section.

- index.html
> add a section on subscription migration for publishers

- index.html
> use versioned URLs for references

- implementation-reports/HUB-mastodon.md
- implementation-reports/PUBLISHER-mastodon.md
- implementation-reports/SUBSCRIBER-mastodon.md
transcribed from IRC report at https://chat.indieweb.org/social/2017-07-12#t1499876947598000
> add implementation report for mastodon

- source.html
- Improve word spelling (Github --> GitHub)
> Improve word spelling (Github --> GitHub)

- source.html
As far as I understand the specification, there are only 2 discovery mechanisms, not three.
> There are only 2 discovery mechanisms, not three

- implementation-reports/HUB-ballerina.md
- implementation-reports/PUBLISHER-ballerina.md
- implementation-reports/SUBSCRIBER-ballerina.md
> Update implementation reports for Ballerina-lang websub components

- implementation-reports/HUB-websubhub.md
Hey folks, stumbled across WebSub and thought it would be fun to use the async benefits of Elixir to build a free & open source public hub. Let me know if I missed anything!
> Add WebSubHub.com to the list of spec'd hubs
